version: '3'

networks:
  laravel:

services:

  nginx:
    image: nginx:stable-alpine
    container_name: webserver
    ports:
    - "8080:80"
    volumes:
      - ./application:/var/www/html
      - ./nginx/default.conf/:/etc/nginx/conf.d/default.conf

    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: dbservice
    restart: unless-stopped
    tty: true
    ports:
    - "3308:3306"
    volumes:
    - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: smart_study
      MYSQL_USER: smart_study
      MYSQL_PASSWORD: mysql12345
      MYSQL_ROOT_PASSWORD: mysql12345
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: phpservice
    volumes:
    - ./application:/var/www/html
    ports:
    - "9000:9000"
    networks:
      - laravel


